pipeline {
    agent any 
    
    tools {
        maven 'maven_3.6.2' 
          }

    stages {
        stage('build') 
        {
            steps {
                echo 'Compiling worker app'
                dir('worker')
                { sh 'mvn compile' }
                   }
        }
        stage('test') 
        {
            steps {
                echo 'Running unit tests for worker'
                dir('worker')
                { sh 'mvn clean test' }
                   }
        }
        stage('package') 
        {
            steps {
                echo 'Packaging worker app'
                dir('worker')
                { sh 'mvn package' }
                   }
        }
                         

            }
           
        
    post { 
        always { 
            archiveArtifacts artifacts: '**/target/*.jar', fingerprint: true
               }
         }  
} 
