pipeline {
    agent any 
    tools {
        maven 'maven_3.6.2' 
        }

    stages {
        stage('build') {
             steps {
                echo 'Compiling worker app'
                dir('worker'){
                sh 'mvn compile'}
                   }
                         }
        stage('test') {
            steps {
                echo 'Running unit tests for worker'
                sh 'mvn test'
                 }
                         }
        stage('package') {
            steps {
                echo 'Packaging worker app'
                sh 'mvn package -D skipTests'
                 }
                         }
           }
        
    post { 
        always { 
            echo 'Build pipeline for worker is complete'
               }
         }  
} 
